### PR TITLE
Start review of tuto

### PR DESCRIPTION
**Pull request by Marie59**
Hello hello @PaulineSGN ! I am putting some descirption in my commits so that you can see why I suggest that ;)

1. Give your pull request a **good title**
    - e.g. "Fix typo in ansible-galaxy tutorial" or "Add new transcriptomics tutorial covering a new sequencing technology"
2. Describe your changes in detail, list anything you still need some help with or things that are still TODO
3. Check that your images are allowed to be re-hosted by the GTN!
4. Still working on it? Make it a **Draft** pull request
   - Once it is ready, choose **Ready for Review**
   - Then the automated tests will run and we will know to review and merge it

### CODE REVIEW

**Comment by Marie59** [comment]
For the last commit with the links there:

`>    [https://zenodo.org/record/5932108/files/wolf_tutorial.zip](https://api.gbif.org/v1/occurrence/download/request/0030809-240506114902167.zip)
>    ```
>    ```
>    https://data.indores.fr/api/access/datafile/9777 : "ceamarc_env.tab"
>    ```
>    ```
>    https://data.indores.fr/api/access/datafile/9756 : "pivot_wider_jupytool_notebook.ipynb"
>    ```
>`
I would advise to clearly put the links in one box and put the name they should have outside of this box  ?

**Comment by Marie59** [comment]
For the unzipping part of your data I have 1 suggestion. I understand that here you wrote this tuto as real life for when people really do have a zip folder. 
I would allow the user to choose between following the tuto if he wants to do it with the zip folder or if he just want to directly get the occurence file with a zenodo link or something like that 
Am I making any sense ?

**Comment by Marie59** [comment]
Moreover for a 2nd version of this tuto I would create a workflow with the "non interesting" data formating part so that the user can directly start the tuto with running this workflow and then directly go to awsome ecoregionalization part ;)

AND also could be great to improve the tool regex find and replace so that you can launch it directly on multiple column !!

**Comment by Marie59** [comment]
`> 5. Unhide the "occurence" data file then modify datatype to select the "tabular" one
`
Explain how to unhide maybe add a tip box => For example me when I unhide I unhide the entire collection so I'd like to know how to only unhidde occurence

**Comment by Marie59** [comment]
For the nex part on **Advanced cut** 
The tool does not detect occurence in my history. I need to drag and drop it ...
probably because I don't unhide well

**Comment by Marie59** [comment]
Now for The **Replace blank space with NAs with Column Regex Find And Replace**:
I think that in the data column name there can be a space so with all the tools finding the space and replacing it with NAs I find my self with weird columns names such as "individualCountNA" and same for all col names I get NA at the end ...
Maybe I did something wrong but I would say that I might not be the only one so maybe put a warning or need to explain more clearly how to do that to avoid mistakes

**Comment by Marie59** [comment]
Issue with the last Advanced cut before launching jupytool => you say to put that your data has a header but for me it does not work when i put "yes" for header I need to put "no" for it to work and to fill in the column  before running advanced cut ...
Maybe it's coming from one of my previous mistake

Add some screenshots allong the way like 2 or 3 to show how the data should look like when you arrive at jupytool part

**Comment by Marie59** [comment]
In the jupytool part explain how to launch the notebook (a tip box can be sufficient I think)

**Comment by Marie59** [comment]
Here for me the jupytool never worked because of the NAs in the columns name ...
Capture d’écran du 2024-07-19 12-02-14

**Comment by Marie59** [comment]
But still I continued with another hisory !
so now here at the end of the jupytool you say :
`>
> 2. Check your output. You must have a tabular file with latitude and longitude in first two columns and the others columns must be taxa.`

How can I check my output ? in the jupytool ? in the galaxy history ? 
Add some screenshots or tips on where to go to check

**Comment by Marie59** [comment]
And that is all for me !! Really enjoyed the ecoregionalization so easy to follow and interesting (that's also why) I don't have that much comments on this part !!

**Comment by PaulineSGN** [comment]
Hello @Marie59 ! Thanks you so much !  I’ll update the training as soon as possible. 
Thanks again for your help !

**Pull request merged**
